version: 2
jobs:
  build:
    working_directory: /go/src/github.com/joedevs/dockerci
    docker:
      - image: circleci/golang:1.12

    environment:
      LOG_FILE_LOCATION: /tmp/test_results

    steps:
      - checkout
      - run: mkdir -p $LOG_FILE_LOCATION
      - restore_cache: # restores saved cache if no changes are detected since last run
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:
            - v1-pkg-cache
      - run: go get -u github.com/golang/dep/cmd/dep
      - run:
          name: run build
          command: |
            dep ensure
            go build -v cmd/main.go
      - run:
          name: run tests
          command: |
            go fmt ./...
            go vet ./...
            go test -v ./...

      - save_cache: # Store cache in the /go/pkg directory
                key: v1-pkg-cache
                paths:
                  - "/go/pkg"
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results